import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeContextProvider } from '@/components/ThemeContext'; // Подключите контекст
import { Topbar } from "@/components/Topbar";
import { CssBaseline } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children }: {
    children: React.ReactNode;
  }
) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeContextProvider>
          <CssBaseline />
          <Topbar />
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
